### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olicash** [wulkano/Kap#997]
**Sentry Issue:** [KAP-7NG](https://sentry.io/organizations/wulkano-l0/issues/1849352311/)

**macOS version:**    High Sierra (10.13)
**Kap version:**      3.3.2

```
Error

Error: Command was killed with SIGABRT (Aborted): /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices list --input --json
dyld: Symbol not found: _$s18IntegerLiteralTypes013ExpressibleByaB0PTl
  Referenced from: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/index.js:114:26)
    at async Object.module.exports.<computed> [as getInputDevices] (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/index.js:10:20)
    at async getAudioDevices (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/devices.js:15:21)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/settings.js:128:21
```

**Comment by sindresorhus** [comment]
Sorry, we're not going to anything with this as we're working on deprecating support for macOS 10.13: https://github.com/wulkano/Kap/issues/838
