### ISSUE TITLE
After upgrade macOS to 13.2, kap do not work

### ISSUE THREAD

**Issue by Gcaufy** [wulkano/kap#1164]
**macOS version:** 13.2
**Kap version:**

#### Current behaviour

<img width="512" alt="image" src="https://user-images.githubusercontent.com/2182004/216225042-c91d3ba8-7a3b-4f3b-8ff0-6dbe3eb99823.png">

```
Uncaught Exception:
TypeError: shortcutToAccelerator is not a function
at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/settings.js:111:54)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/analytics.js:9:20)
at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

#### Workaround

it works before macOS upgraded.  and I have tried reinstall it many times.

**Comment by agurtovoy** [comment]
Can confirm that the same build (3.6.0.1846) works on Ventura 13.1 and crashes with the error above on 13.2.1 (22D68).

**Comment by carstenhag** [comment]
There's a workaround available here: https://github.com/wulkano/Kap/issues/1095#issuecomment-1216312778
